/**
 * build.js
 * Reads every Markdown file in /posts, turns it into a blog post object,
 * and writes /public/blog-data.js (window.BLOG_POSTS / window.BLOG_TAGS).
 * Also copies index.html into /public so the whole site deploys from one folder.
 *
 * Run with:  npm run build
 * No dependencies — plain Node.js (fs/path only).
 */

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const POSTS_DIR = path.join(ROOT, 'posts');
const OUT_DIR = path.join(ROOT, 'public');

function parseFrontmatter(raw) {
  const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!match) return { data: {}, content: raw.trim() };
  const [, fmBlock, body] = match;
  const data = {};
  fmBlock.split('\n').forEach((line) => {
    const idx = line.indexOf(':');
    if (idx === -1) return;
    const key = line.slice(0, idx).trim();
    let val = line.slice(idx + 1).trim();
    if (val === 'true') val = true;
    else if (val === 'false') val = false;
    else if (key === 'tags') val = val.split(',').map((t) => t.trim()).filter(Boolean);
    data[key] = val;
  });
  return { data, content: body.trim() };
}

function estimateReadTime(md) {
  const words = md
    .replace(/```[\s\S]*?```/g, ' ')       // drop code blocks
    .replace(/[#*`_>\[\]()-]/g, ' ')        // drop markdown punctuation
    .split(/\s+/)
    .filter(Boolean).length;
  return Math.max(1, Math.round(words / 200)) + ' min';
}

function autoExcerpt(md) {
  const firstPara = md
    .split(/\n\s*\n/)
    .map((p) => p.trim())
    .find((p) => p && !p.startsWith('#') && !p.startsWith('```'));
  if (!firstPara) return '';
  const plain = firstPara.replace(/[#*`_\[\]()>-]/g, '').trim();
  return plain.length > 160 ? plain.slice(0, 157).trim() + '…' : plain;
}

function build() {
  fs.mkdirSync(OUT_DIR, { recursive: true });

  let posts = [];

  if (!fs.existsSync(POSTS_DIR)) {
    console.log('No /posts directory found — blog will show no posts until you add one.');
  } else {
    const files = fs
      .readdirSync(POSTS_DIR)
      .filter((f) => f.endsWith('.md') && !f.startsWith('_'));

    posts = files.map((file) => {
      const raw = fs.readFileSync(path.join(POSTS_DIR, file), 'utf8');
      const { data, content } = parseFrontmatter(raw);

      if (!data.title) console.warn(`⚠️  ${file}: missing "title" in frontmatter.`);
      if (!data.date) console.warn(`⚠️  ${file}: missing "date" in frontmatter (YYYY-MM-DD).`);

      return {
        id: data.id || file.replace(/\.md$/, ''),
        sample: data.sample === true,
        featured: data.featured === true,
        title: data.title || file,
        subtitle: data.subtitle || '',
        date: data.date || '1970-01-01',
        readTime: data.readtime || data.readTime || estimateReadTime(content),
        tags: Array.isArray(data.tags) ? data.tags : [],
        excerpt: data.excerpt || autoExcerpt(content),
        content,
      };
    });

    posts.sort((a, b) => new Date(b.date) - new Date(a.date));
  }

  const tagSet = new Set();
  posts.forEach((p) => p.tags.forEach((t) => tagSet.add(t)));

  const out =
    `// Auto-generated by build.js — do not edit by hand.\n` +
    `window.BLOG_POSTS = ${JSON.stringify(posts, null, 2)};\n` +
    `window.BLOG_TAGS = ${JSON.stringify([...tagSet], null, 2)};\n`;

  fs.writeFileSync(path.join(OUT_DIR, 'blog-data.js'), out);
  fs.copyFileSync(path.join(ROOT, 'index.html'), path.join(OUT_DIR, 'index.html'));

  console.log(`✔ Built ${posts.length} post(s) → public/blog-data.js`);
  console.log('✔ Copied index.html → public/index.html');

  const adminSrc = path.join(ROOT, 'admin.html');
  if (fs.existsSync(adminSrc)) {
    fs.copyFileSync(adminSrc, path.join(OUT_DIR, 'admin.html'));
    console.log('✔ Copied admin.html → public/admin.html');
  }
}

build();
